import path from 'node:path'
import { mkdirSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import * as pty from 'node-pty'
import { createId } from '@/base/ids'
import type {
  TerminalEvent,
  TerminalRequest,
} from '@/base/protocol'
import type { ID, Slab } from '@/base/types'
import { expandHome } from './paths'
import { getDefaultProgram } from './program'

export type TerminalManagerOptions = {
  emit(event: TerminalEvent): void
}

type RuntimeSlab = {
  slab: Slab
  pty: pty.IPty
  outputBuffer: string[]
  createdAt: number
}

/**
 * Set up a Term-controlled init directory and write per-
 * shell startup files that source the user's normal config
 * and then install the OSC 7 cwd hook. Doing the injection
 * at shell-startup time (via ZDOTDIR / --rcfile /
 * --init-command) means the setup never appears in the
 * visible terminal — the user sees their normal prompt and
 * nothing else.
 *
 * Without OSC 7, Term has no way to know when the user
 * `cd`s into a new directory, so persisted cwds get stuck
 * at the initial spawn location and `claude --resume`
 * (and anything else that resolves state by cwd) breaks
 * after the first cd.
 *
 * Supported: zsh (via ZDOTDIR), bash (via --rcfile), fish
 * (via --init-command source <file>). For any other shell
 * Term falls back to "initial-cwd-only" tracking — the
 * shell still runs cleanly, just without live cd tracking.
 */
let cachedShellInitDir: string | null = null
function ensureShellInitDir(): string {
  if (cachedShellInitDir) return cachedShellInitDir
  const dir = path.join(tmpdir(), `term-shell-init-${process.pid}`)
  mkdirSync(dir, { recursive: true })

  // ── zsh: ZDOTDIR/.zshrc ───────────────────────────────
  writeFileSync(
    path.join(dir, '.zshrc'),
    [
      '# Auto-generated by Term. Sources the user',
      '# normal .zshrc, then adds the OSC 7 cwd hook.',
      '[ -f "$HOME/.zshrc" ] && source "$HOME/.zshrc"',
      '',
      '_term_cwd() {',
      `  printf '\\033]7;file://%s%s\\a' "\${HOSTNAME:-\${HOST}}" "$PWD"`,
      '}',
      'typeset -ga chpwd_functions 2>/dev/null',
      'chpwd_functions+=(_term_cwd) 2>/dev/null',
      '_term_cwd',
      '',
    ].join('\n'),
    'utf-8',
  )

  // ── bash: rcfile sourced via --rcfile ─────────────────
  // bash --rcfile <file> -i overrides ~/.bashrc; we source
  // the user's normal config ourselves so aliases, prompt,
  // completions all still load. Also pick up .bash_profile
  // since some users put PATH there and expect login-shell
  // semantics inside their terminal.
  writeFileSync(
    path.join(dir, 'term-bashrc'),
    [
      '# Auto-generated by Term. Sources the user',
      '# normal bash config, then adds the OSC 7 cwd hook.',
      '[ -f /etc/bashrc ] && source /etc/bashrc',
      '[ -f "$HOME/.bashrc" ] && source "$HOME/.bashrc"',
      '# .bash_profile is normally sourced only for login',
      '# shells, but with --rcfile bash skips it. Pull it in',
      '# manually so PATH / nvm / pyenv inits still happen.',
      'if [ -f "$HOME/.bash_profile" ] && [ -z "$TERM_BASH_PROFILE_SOURCED" ]; then',
      '  export TERM_BASH_PROFILE_SOURCED=1',
      '  source "$HOME/.bash_profile"',
      'fi',
      '',
      '_term_cwd() {',
      `  printf '\\033]7;file://%s%s\\007' "\${HOSTNAME}" "$PWD"`,
      '}',
      '# Prepend so the user PROMPT_COMMAND still runs.',
      'PROMPT_COMMAND="_term_cwd${PROMPT_COMMAND:+; $PROMPT_COMMAND}"',
      '_term_cwd',
      '',
    ].join('\n'),
    'utf-8',
  )

  // ── fish: init script sourced via --init-command ──────
  // fish's --init-command runs after the normal config
  // pipeline, so the user's config.fish is loaded first.
  writeFileSync(
    path.join(dir, 'term-fish-init.fish'),
    [
      '# Auto-generated by Term — emits OSC 7 on every PWD change.',
      'function _term_cwd --on-variable PWD',
      `  printf '\\e]7;file://%s%s\\a' (hostname) "$PWD"`,
      'end',
      '_term_cwd',
      '',
    ].join('\n'),
    'utf-8',
  )

  cachedShellInitDir = dir
  return dir
}

/**
 * Build the shell-injection bits — extra args + env vars
 * Term prepends to pty.spawn for a given program. Only
 * fires when the caller hasn't supplied their own args
 * (custom invocations like `bash -c '<one-off>'` shouldn't
 * be wrapped). Always sets ZDOTDIR — harmless for non-zsh
 * shells (they ignore it).
 */
function buildShellInjection({
  program,
  args,
}: {
  program: string
  args: string[]
}): { args: string[]; env: Record<string, string> } {
  const shell = path.basename(program)
  const dir = ensureShellInitDir()
  // Always set ZDOTDIR so any zsh launched as a sub-shell
  // also picks up the hook. Bash / fish ignore this.
  const env: Record<string, string> = { ZDOTDIR: dir }
  // Only inject extra args when the caller didn't pass
  // their own. Custom args usually mean "run this one
  // command" and our --rcfile would derail that.
  if (args.length > 0) {
    return { args, env }
  }
  if (shell === 'bash') {
    return {
      args: ['--rcfile', path.join(dir, 'term-bashrc'), '-i'],
      env,
    }
  }
  if (shell === 'fish') {
    return {
      args: [
        '--init-command',
        `source ${path.join(dir, 'term-fish-init.fish')}`,
      ],
      env,
    }
  }
  // zsh works purely via ZDOTDIR — no arg injection needed.
  // Anything else gets initial-cwd-only tracking.
  return { args: [], env }
}

export class TerminalManager {
  private slabs = new Map<ID, RuntimeSlab>()

  constructor(private options: TerminalManagerOptions) {}

  async handle(request: TerminalRequest): Promise<unknown> {
    switch (request.type) {
      case 'slab:create':
        return this.createSlab(request.payload)
      case 'slab:write':
        return this.write(request.payload.slabId, request.payload.data)
      case 'slab:resize':
        return this.resize(
          request.payload.slabId,
          request.payload.cols,
          request.payload.rows,
        )
      case 'slab:kill':
        return this.kill(request.payload.slabId)
      case 'slab:restart':
        return this.restart(request.payload.slabId)
      case 'workspace:create':
      case 'workspace:open':
      case 'workspace:list':
        throw new Error(
          `Workspace store not wired into manager: ${request.type}`,
        )
      default:
        assertNever(request)
    }
  }

  async createSlab(input: {
    /** Pre-generated slab id from compileWorkspace. When the
     *  caller compiled a workspace and sent slabIdByName to
     *  the renderer, the same id MUST be used here so reads
     *  / writes from the renderer match the runtime slab. */
    id?: ID
    workspaceId: ID
    tabId: ID
    name?: string
    cwd?: string
    program?: string
    args?: string[]
    command?: string
    env?: Record<string, string>
    cols: number
    rows: number
  }): Promise<Slab> {
    const id = input.id ?? createId('slab')
    // Treat empty string AND undefined as "use default shell"
    // — compileWorkspace sets program to '' when the user
    // didn't specify one. pty.spawn('') would silently do
    // nothing (no shell ever starts, xterm sits empty).
    const program =
      input.program && input.program.length > 0
        ? input.program
        : getDefaultProgram()
    const cwd = expandHome(input.cwd ?? process.cwd())

    const slab: Slab = {
      id,
      workspaceId: input.workspaceId,
      tabId: input.tabId,
      name: input.name ?? path.basename(cwd),
      cwd,
      program,
      args: input.args ?? [],
      command: input.command,
      env: input.env,
      cols: input.cols,
      rows: input.rows,
      status: 'starting',
      createdAt: Date.now(),
      updatedAt: Date.now(),
    }

    this.emitStatus(id, 'starting')

    // Cross-shell OSC 7 cwd injection. For zsh, bash, and
    // fish, Term points the shell at a startup script that
    // sources the user's normal config and then installs a
    // hook that emits OSC 7 on every cd. Any other shell
    // gets initial-cwd-only tracking.
    const inject = buildShellInjection({
      program,
      args: input.args ?? [],
    })

    const proc = pty.spawn(program, inject.args, {
      name: 'xterm-256color',
      cols: input.cols,
      rows: input.rows,
      cwd,
      env: {
        ...process.env,
        TERM: 'xterm-256color',
        COLORTERM: 'truecolor',
        TERM_PROGRAM: 'cluesurf-term',
        // Disable zsh's "partial line" indicator. zsh
        // prints a highlighted `%` and inserts a newline
        // whenever the previous output didn't end in \n —
        // e.g. when xterm sends its initial resize before
        // the first prompt fires, or when an OSC reply
        // doesn't include a trailing newline. Cosmetic
        // glitch only, but it pushes the first prompt
        // onto line 2, which the user reads as "the
        // cursor went to the wrong place". Setting an
        // empty mark suppresses both the % and the
        // forced newline.
        PROMPT_EOL_MARK: '',
        ...inject.env,
        ...input.env,
      } as Record<string, string>,
    })

    const runtime: RuntimeSlab = {
      slab,
      pty: proc,
      outputBuffer: [],
      createdAt: Date.now(),
    }
    this.slabs.set(id, runtime)

    proc.onData(data => {
      runtime.outputBuffer.push(data)
      if (runtime.outputBuffer.length > 5000) {
        runtime.outputBuffer.splice(0, runtime.outputBuffer.length - 5000)
      }
      this.options.emit({
        type: 'slab:data',
        payload: {
          slabId: id,
          data,
        },
      })
    })

    proc.onExit(event => {
      slab.status = 'exited'
      slab.updatedAt = Date.now()
      this.options.emit({
        type: 'slab:exit',
        payload: {
          slabId: id,
          exitCode: event.exitCode,
          signal: event.signal,
        },
      })
      this.emitStatus(id, 'exited')
    })

    slab.status = 'running'
    this.emitStatus(id, 'running')

    // OSC 7 cwd hook is now installed via $ZDOTDIR's
    // .zshrc (see `ensureTermZdotdir` above) — invisible
    // because it runs during shell startup, not as
    // user-typed input. No post-spawn write needed.

    if (input.command) {
      proc.write(`${input.command}\r`)
    }

    return slab
  }

  write(slabId: ID, data: string): null {
    const runtime = this.mustGetSlab(slabId)
    runtime.pty.write(data)
    return null
  }

  resize(slabId: ID, cols: number, rows: number): null {
    const runtime = this.mustGetSlab(slabId)
    const safeCols = Math.max(2, Math.floor(cols))
    const safeRows = Math.max(1, Math.floor(rows))
    runtime.slab.cols = safeCols
    runtime.slab.rows = safeRows
    runtime.slab.updatedAt = Date.now()
    runtime.pty.resize(safeCols, safeRows)
    return null
  }

  kill(slabId: ID): null {
    const runtime = this.mustGetSlab(slabId)
    runtime.pty.kill()
    this.slabs.delete(slabId)
    return null
  }

  async restart(slabId: ID): Promise<Slab> {
    const runtime = this.mustGetSlab(slabId)
    const slab = runtime.slab
    runtime.pty.kill()
    this.slabs.delete(slabId)

    return this.createSlab({
      workspaceId: slab.workspaceId,
      tabId: slab.tabId,
      name: slab.name,
      cwd: slab.cwd,
      program: slab.program,
      args: slab.args,
      command: slab.command,
      env: slab.env,
      cols: slab.cols,
      rows: slab.rows,
    })
  }

  async shutdown(): Promise<void> {
    for (const runtime of this.slabs.values()) {
      runtime.pty.kill()
    }
    this.slabs.clear()
  }

  getOutputBuffer(slabId: ID): string[] {
    return [...this.mustGetSlab(slabId).outputBuffer]
  }

  listSlabs(): Slab[] {
    return [...this.slabs.values()].map(runtime => runtime.slab)
  }

  private mustGetSlab(slabId: ID): RuntimeSlab {
    const runtime = this.slabs.get(slabId)
    if (!runtime) {
      throw new Error(`Slab not found: ${slabId}`)
    }
    return runtime
  }

  private emitStatus(slabId: ID, status: Slab['status']): void {
    this.options.emit({
      type: 'slab:status',
      payload: {
        slabId,
        status,
      },
    })
  }
}

function assertNever(value: never): never {
  throw new Error(`Unhandled request: ${JSON.stringify(value)}`)
}
